/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DietaryTag = { 'veg' : null } |
  { 'halal' : null } |
  { 'vegan' : null } |
  { 'dairy_free' : null } |
  { 'spicy' : null } |
  { 'gluten_free' : null };
export type ExternalBlob = Uint8Array;
export interface FoodItem {
  'id' : FoodItemId,
  'name' : string,
  'createdAt' : Timestamp,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'dietaryTags' : Array<DietaryTag>,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type FoodItemId = bigint;
export interface FoodItemInput {
  'name' : string,
  'description' : string,
  'restaurantId' : RestaurantId,
  'dietaryTags' : Array<DietaryTag>,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface OperatingHours {
  'closeTime' : string,
  'daysOpen' : Array<string>,
  'openTime' : string,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'taxes' : bigint,
  'deliveryAddress' : string,
  'total' : bigint,
  'paymentStatus' : PaymentStatus,
  'deliveryFee' : bigint,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'specialInstructions' : string,
  'restaurantName' : string,
  'customerId' : UserId,
  'phone' : string,
  'items' : Array<OrderItem>,
  'stripeSessionId' : [] | [string],
  'subtotal' : bigint,
}
export type OrderId = bigint;
export interface OrderInput {
  'deliveryAddress' : string,
  'restaurantId' : RestaurantId,
  'specialInstructions' : string,
  'phone' : string,
  'items' : Array<OrderItemInput>,
  'stripeSessionId' : [] | [string],
}
export interface OrderItem {
  'name' : string,
  'foodItemId' : FoodItemId,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OrderItemInput {
  'foodItemId' : FoodItemId,
  'quantity' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'out_for_delivery' : null } |
  { 'delivered' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface Restaurant {
  'id' : RestaurantId,
  'deliveryFee' : bigint,
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'cuisineType' : string,
  'description' : string,
  'isActive' : boolean,
  'deliveryTimeMinutes' : bigint,
  'updatedAt' : Timestamp,
  'address' : string,
  'minimumOrder' : bigint,
  'image' : ExternalBlob,
  'phone' : string,
  'operatingHours' : OperatingHours,
}
export type RestaurantId = bigint;
export interface RestaurantInput {
  'deliveryFee' : bigint,
  'ownerId' : UserId,
  'name' : string,
  'cuisineType' : string,
  'description' : string,
  'deliveryTimeMinutes' : bigint,
  'address' : string,
  'minimumOrder' : bigint,
  'image' : ExternalBlob,
  'phone' : string,
  'operatingHours' : OperatingHours,
}
export interface RestaurantRatingStats {
  'restaurantId' : RestaurantId,
  'averageRating' : number,
  'reviewCount' : bigint,
}
export interface RestaurantSummary {
  'id' : RestaurantId,
  'deliveryFee' : bigint,
  'name' : string,
  'cuisineType' : string,
  'isActive' : boolean,
  'deliveryTimeMinutes' : bigint,
  'averageRating' : number,
  'minimumOrder' : bigint,
  'image' : ExternalBlob,
  'reviewCount' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'customerName' : string,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : string,
  'customerId' : UserId,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ReviewInput {
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : string,
  'rating' : bigint,
}
export interface SearchFilters {
  'minRating' : [] | [number],
  'sortBy' : [] | [SortOption],
  'cuisineType' : [] | [string],
  'maxPrice' : [] | [bigint],
  'dietaryTags' : Array<DietaryTag>,
  'category' : [] | [string],
  'minPrice' : [] | [bigint],
  'searchQuery' : [] | [string],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SortOption = { 'deliveryTime' : null } |
  { 'priceDesc' : null } |
  { 'rating' : null } |
  { 'priceAsc' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'isDeleted' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
  'defaultAddress' : string,
}
export interface UserProfileInput {
  'name' : string,
  'email' : string,
  'phone' : string,
  'defaultAddress' : string,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'restaurant_owner' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignUserRole' : ActorMethod<[UserId, UserRole], undefined>,
  'confirmOrderPayment' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createFoodItem' : ActorMethod<[FoodItemInput], FoodItemId>,
  'createRestaurant' : ActorMethod<[RestaurantInput], RestaurantId>,
  'deleteFoodItem' : ActorMethod<[FoodItemId], undefined>,
  'deleteRestaurant' : ActorMethod<[RestaurantId], undefined>,
  'deleteReview' : ActorMethod<[ReviewId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getFoodItem' : ActorMethod<[FoodItemId], [] | [FoodItem]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [Restaurant]>,
  'getRestaurantRatingStats' : ActorMethod<
    [RestaurantId],
    [] | [RestaurantRatingStats]
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<
    [[] | [RestaurantId], [] | [OrderStatus]],
    Array<Order>
  >,
  'listAllReviews' : ActorMethod<[], Array<Review>>,
  'listFoodItems' : ActorMethod<[RestaurantId], Array<FoodItem>>,
  'listMyOrders' : ActorMethod<[[] | [OrderStatus]], Array<Order>>,
  'listRestaurantReviews' : ActorMethod<[RestaurantId], Array<Review>>,
  'listRestaurants' : ActorMethod<
    [[] | [SearchFilters]],
    Array<RestaurantSummary>
  >,
  'listUsers' : ActorMethod<[[] | [UserRole]], Array<UserProfile>>,
  'placeOrder' : ActorMethod<[OrderInput], OrderId>,
  'postReview' : ActorMethod<[ReviewInput], ReviewId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'searchFoodItems' : ActorMethod<[SearchFilters], Array<FoodItem>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'softDeleteUser' : ActorMethod<[UserId], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateFoodItem' : ActorMethod<[FoodItemId, FoodItemInput], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateRestaurant' : ActorMethod<[RestaurantId, RestaurantInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];