/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'restaurant_owner' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const RestaurantId = IDL.Nat;
export const DietaryTag = IDL.Variant({
  'veg' : IDL.Null,
  'halal' : IDL.Null,
  'vegan' : IDL.Null,
  'dairy_free' : IDL.Null,
  'spicy' : IDL.Null,
  'gluten_free' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FoodItemInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'dietaryTags' : IDL.Vec(DietaryTag),
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const FoodItemId = IDL.Nat;
export const OperatingHours = IDL.Record({
  'closeTime' : IDL.Text,
  'daysOpen' : IDL.Vec(IDL.Text),
  'openTime' : IDL.Text,
});
export const RestaurantInput = IDL.Record({
  'deliveryFee' : IDL.Nat,
  'ownerId' : UserId,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'deliveryTimeMinutes' : IDL.Nat,
  'address' : IDL.Text,
  'minimumOrder' : IDL.Nat,
  'image' : ExternalBlob,
  'phone' : IDL.Text,
  'operatingHours' : OperatingHours,
});
export const ReviewId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'isDeleted' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'defaultAddress' : IDL.Text,
});
export const FoodItem = IDL.Record({
  'id' : FoodItemId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'dietaryTags' : IDL.Vec(DietaryTag),
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'out_for_delivery' : IDL.Null,
  'delivered' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'foodItemId' : FoodItemId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'taxes' : IDL.Nat,
  'deliveryAddress' : IDL.Text,
  'total' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'deliveryFee' : IDL.Nat,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'specialInstructions' : IDL.Text,
  'restaurantName' : IDL.Text,
  'customerId' : UserId,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'subtotal' : IDL.Nat,
});
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'deliveryFee' : IDL.Nat,
  'ownerId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'deliveryTimeMinutes' : IDL.Nat,
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
  'minimumOrder' : IDL.Nat,
  'image' : ExternalBlob,
  'phone' : IDL.Text,
  'operatingHours' : OperatingHours,
});
export const RestaurantRatingStats = IDL.Record({
  'restaurantId' : RestaurantId,
  'averageRating' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'customerName' : IDL.Text,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : IDL.Text,
  'customerId' : UserId,
  'rating' : IDL.Nat,
});
export const SortOption = IDL.Variant({
  'deliveryTime' : IDL.Null,
  'priceDesc' : IDL.Null,
  'rating' : IDL.Null,
  'priceAsc' : IDL.Null,
});
export const SearchFilters = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'sortBy' : IDL.Opt(SortOption),
  'cuisineType' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'dietaryTags' : IDL.Vec(DietaryTag),
  'category' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const RestaurantSummary = IDL.Record({
  'id' : RestaurantId,
  'deliveryFee' : IDL.Nat,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'isActive' : IDL.Bool,
  'deliveryTimeMinutes' : IDL.Nat,
  'averageRating' : IDL.Float64,
  'minimumOrder' : IDL.Nat,
  'image' : ExternalBlob,
  'reviewCount' : IDL.Nat,
});
export const OrderItemInput = IDL.Record({
  'foodItemId' : FoodItemId,
  'quantity' : IDL.Nat,
});
export const OrderInput = IDL.Record({
  'deliveryAddress' : IDL.Text,
  'restaurantId' : RestaurantId,
  'specialInstructions' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItemInput),
  'stripeSessionId' : IDL.Opt(IDL.Text),
});
export const ReviewInput = IDL.Record({
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'defaultAddress' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignUserRole' : IDL.Func([UserId, UserRole], [], []),
  'confirmOrderPayment' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createFoodItem' : IDL.Func([FoodItemInput], [FoodItemId], []),
  'createRestaurant' : IDL.Func([RestaurantInput], [RestaurantId], []),
  'deleteFoodItem' : IDL.Func([FoodItemId], [], []),
  'deleteRestaurant' : IDL.Func([RestaurantId], [], []),
  'deleteReview' : IDL.Func([ReviewId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFoodItem' : IDL.Func([FoodItemId], [IDL.Opt(FoodItem)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getRestaurant' : IDL.Func([RestaurantId], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantRatingStats' : IDL.Func(
      [RestaurantId],
      [IDL.Opt(RestaurantRatingStats)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllOrders' : IDL.Func(
      [IDL.Opt(RestaurantId), IDL.Opt(OrderStatus)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listFoodItems' : IDL.Func([RestaurantId], [IDL.Vec(FoodItem)], ['query']),
  'listMyOrders' : IDL.Func(
      [IDL.Opt(OrderStatus)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'listRestaurantReviews' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'listRestaurants' : IDL.Func(
      [IDL.Opt(SearchFilters)],
      [IDL.Vec(RestaurantSummary)],
      ['query'],
    ),
  'listUsers' : IDL.Func(
      [IDL.Opt(UserRole)],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([OrderInput], [OrderId], []),
  'postReview' : IDL.Func([ReviewInput], [ReviewId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'searchFoodItems' : IDL.Func([SearchFilters], [IDL.Vec(FoodItem)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'softDeleteUser' : IDL.Func([UserId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFoodItem' : IDL.Func([FoodItemId, FoodItemInput], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateRestaurant' : IDL.Func([RestaurantId, RestaurantInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'restaurant_owner' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const RestaurantId = IDL.Nat;
  const DietaryTag = IDL.Variant({
    'veg' : IDL.Null,
    'halal' : IDL.Null,
    'vegan' : IDL.Null,
    'dairy_free' : IDL.Null,
    'spicy' : IDL.Null,
    'gluten_free' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FoodItemInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'dietaryTags' : IDL.Vec(DietaryTag),
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const FoodItemId = IDL.Nat;
  const OperatingHours = IDL.Record({
    'closeTime' : IDL.Text,
    'daysOpen' : IDL.Vec(IDL.Text),
    'openTime' : IDL.Text,
  });
  const RestaurantInput = IDL.Record({
    'deliveryFee' : IDL.Nat,
    'ownerId' : UserId,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'deliveryTimeMinutes' : IDL.Nat,
    'address' : IDL.Text,
    'minimumOrder' : IDL.Nat,
    'image' : ExternalBlob,
    'phone' : IDL.Text,
    'operatingHours' : OperatingHours,
  });
  const ReviewId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'isDeleted' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'defaultAddress' : IDL.Text,
  });
  const FoodItem = IDL.Record({
    'id' : FoodItemId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'updatedAt' : Timestamp,
    'dietaryTags' : IDL.Vec(DietaryTag),
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'out_for_delivery' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'foodItemId' : FoodItemId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'taxes' : IDL.Nat,
    'deliveryAddress' : IDL.Text,
    'total' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'deliveryFee' : IDL.Nat,
    'createdAt' : Timestamp,
    'restaurantId' : RestaurantId,
    'updatedAt' : Timestamp,
    'specialInstructions' : IDL.Text,
    'restaurantName' : IDL.Text,
    'customerId' : UserId,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'subtotal' : IDL.Nat,
  });
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'deliveryFee' : IDL.Nat,
    'ownerId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'deliveryTimeMinutes' : IDL.Nat,
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
    'minimumOrder' : IDL.Nat,
    'image' : ExternalBlob,
    'phone' : IDL.Text,
    'operatingHours' : OperatingHours,
  });
  const RestaurantRatingStats = IDL.Record({
    'restaurantId' : RestaurantId,
    'averageRating' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'customerName' : IDL.Text,
    'createdAt' : Timestamp,
    'orderId' : OrderId,
    'restaurantId' : RestaurantId,
    'comment' : IDL.Text,
    'customerId' : UserId,
    'rating' : IDL.Nat,
  });
  const SortOption = IDL.Variant({
    'deliveryTime' : IDL.Null,
    'priceDesc' : IDL.Null,
    'rating' : IDL.Null,
    'priceAsc' : IDL.Null,
  });
  const SearchFilters = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'sortBy' : IDL.Opt(SortOption),
    'cuisineType' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'dietaryTags' : IDL.Vec(DietaryTag),
    'category' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const RestaurantSummary = IDL.Record({
    'id' : RestaurantId,
    'deliveryFee' : IDL.Nat,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'isActive' : IDL.Bool,
    'deliveryTimeMinutes' : IDL.Nat,
    'averageRating' : IDL.Float64,
    'minimumOrder' : IDL.Nat,
    'image' : ExternalBlob,
    'reviewCount' : IDL.Nat,
  });
  const OrderItemInput = IDL.Record({
    'foodItemId' : FoodItemId,
    'quantity' : IDL.Nat,
  });
  const OrderInput = IDL.Record({
    'deliveryAddress' : IDL.Text,
    'restaurantId' : RestaurantId,
    'specialInstructions' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItemInput),
    'stripeSessionId' : IDL.Opt(IDL.Text),
  });
  const ReviewInput = IDL.Record({
    'orderId' : OrderId,
    'restaurantId' : RestaurantId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'defaultAddress' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignUserRole' : IDL.Func([UserId, UserRole], [], []),
    'confirmOrderPayment' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createFoodItem' : IDL.Func([FoodItemInput], [FoodItemId], []),
    'createRestaurant' : IDL.Func([RestaurantInput], [RestaurantId], []),
    'deleteFoodItem' : IDL.Func([FoodItemId], [], []),
    'deleteRestaurant' : IDL.Func([RestaurantId], [], []),
    'deleteReview' : IDL.Func([ReviewId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFoodItem' : IDL.Func([FoodItemId], [IDL.Opt(FoodItem)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'getRestaurantRatingStats' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(RestaurantRatingStats)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllOrders' : IDL.Func(
        [IDL.Opt(RestaurantId), IDL.Opt(OrderStatus)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listFoodItems' : IDL.Func([RestaurantId], [IDL.Vec(FoodItem)], ['query']),
    'listMyOrders' : IDL.Func(
        [IDL.Opt(OrderStatus)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'listRestaurantReviews' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'listRestaurants' : IDL.Func(
        [IDL.Opt(SearchFilters)],
        [IDL.Vec(RestaurantSummary)],
        ['query'],
      ),
    'listUsers' : IDL.Func(
        [IDL.Opt(UserRole)],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([OrderInput], [OrderId], []),
    'postReview' : IDL.Func([ReviewInput], [ReviewId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'searchFoodItems' : IDL.Func(
        [SearchFilters],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'seedSampleData' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'softDeleteUser' : IDL.Func([UserId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFoodItem' : IDL.Func([FoodItemId, FoodItemInput], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateRestaurant' : IDL.Func([RestaurantId, RestaurantInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };