/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OrderId = bigint;
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface OrderItem {
    name: string;
    foodItemId: FoodItemId;
    quantity: bigint;
    price: bigint;
}
export interface OrderInput {
    deliveryAddress: string;
    restaurantId: RestaurantId;
    specialInstructions: string;
    phone: string;
    items: Array<OrderItemInput>;
    stripeSessionId?: string;
}
export interface OrderItemInput {
    foodItemId: FoodItemId;
    quantity: bigint;
}
export interface RestaurantInput {
    deliveryFee: bigint;
    ownerId: UserId;
    name: string;
    cuisineType: string;
    description: string;
    deliveryTimeMinutes: bigint;
    address: string;
    minimumOrder: bigint;
    image: ExternalBlob;
    phone: string;
    operatingHours: OperatingHours;
}
export type RestaurantId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface RestaurantRatingStats {
    restaurantId: RestaurantId;
    averageRating: number;
    reviewCount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface FoodItem {
    id: FoodItemId;
    name: string;
    createdAt: Timestamp;
    isAvailable: boolean;
    description: string;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    dietaryTags: Array<DietaryTag>;
    category: string;
    image: ExternalBlob;
    price: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type ReviewId = bigint;
export interface OperatingHours {
    closeTime: string;
    daysOpen: Array<string>;
    openTime: string;
}
export interface Review {
    id: ReviewId;
    customerName: string;
    createdAt: Timestamp;
    orderId: OrderId;
    restaurantId: RestaurantId;
    comment: string;
    customerId: UserId;
    rating: bigint;
}
export interface SearchFilters {
    minRating?: number;
    sortBy?: SortOption;
    cuisineType?: string;
    maxPrice?: bigint;
    dietaryTags: Array<DietaryTag>;
    category?: string;
    minPrice?: bigint;
    searchQuery?: string;
}
export type FoodItemId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Restaurant {
    id: RestaurantId;
    deliveryFee: bigint;
    ownerId: UserId;
    name: string;
    createdAt: Timestamp;
    cuisineType: string;
    description: string;
    isActive: boolean;
    deliveryTimeMinutes: bigint;
    updatedAt: Timestamp;
    address: string;
    minimumOrder: bigint;
    image: ExternalBlob;
    phone: string;
    operatingHours: OperatingHours;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    taxes: bigint;
    deliveryAddress: string;
    total: bigint;
    paymentStatus: PaymentStatus;
    deliveryFee: bigint;
    createdAt: Timestamp;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    specialInstructions: string;
    restaurantName: string;
    customerId: UserId;
    phone: string;
    items: Array<OrderItem>;
    stripeSessionId?: string;
    subtotal: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface FoodItemInput {
    name: string;
    description: string;
    restaurantId: RestaurantId;
    dietaryTags: Array<DietaryTag>;
    category: string;
    image: ExternalBlob;
    price: bigint;
}
export interface RestaurantSummary {
    id: RestaurantId;
    deliveryFee: bigint;
    name: string;
    cuisineType: string;
    isActive: boolean;
    deliveryTimeMinutes: bigint;
    averageRating: number;
    minimumOrder: bigint;
    image: ExternalBlob;
    reviewCount: bigint;
}
export interface UserProfileInput {
    name: string;
    email: string;
    phone: string;
    defaultAddress: string;
}
export interface UserProfile {
    id: UserId;
    isDeleted: boolean;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    phone: string;
    defaultAddress: string;
}
export interface ReviewInput {
    orderId: OrderId;
    restaurantId: RestaurantId;
    comment: string;
    rating: bigint;
}
export enum DietaryTag {
    veg = "veg",
    halal = "halal",
    vegan = "vegan",
    dairy_free = "dairy_free",
    spicy = "spicy",
    gluten_free = "gluten_free"
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    out_for_delivery = "out_for_delivery",
    delivered = "delivered"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum SortOption {
    deliveryTime = "deliveryTime",
    priceDesc = "priceDesc",
    rating = "rating",
    priceAsc = "priceAsc"
}
export enum UserRole {
    admin = "admin",
    customer = "customer",
    restaurant_owner = "restaurant_owner"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignUserRole(userId: UserId, role: UserRole): Promise<void>;
    confirmOrderPayment(sessionId: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createFoodItem(input: FoodItemInput): Promise<FoodItemId>;
    createRestaurant(input: RestaurantInput): Promise<RestaurantId>;
    deleteFoodItem(foodItemId: FoodItemId): Promise<void>;
    deleteRestaurant(restaurantId: RestaurantId): Promise<void>;
    deleteReview(reviewId: ReviewId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getFoodItem(foodItemId: FoodItemId): Promise<FoodItem | null>;
    getOrder(orderId: OrderId): Promise<Order | null>;
    getRestaurant(restaurantId: RestaurantId): Promise<Restaurant | null>;
    getRestaurantRatingStats(restaurantId: RestaurantId): Promise<RestaurantRatingStats | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllOrders(restaurantFilter: RestaurantId | null, statusFilter: OrderStatus | null): Promise<Array<Order>>;
    listAllReviews(): Promise<Array<Review>>;
    listFoodItems(restaurantId: RestaurantId): Promise<Array<FoodItem>>;
    listMyOrders(statusFilter: OrderStatus | null): Promise<Array<Order>>;
    listRestaurantReviews(restaurantId: RestaurantId): Promise<Array<Review>>;
    listRestaurants(filters: SearchFilters | null): Promise<Array<RestaurantSummary>>;
    listUsers(roleFilter: UserRole | null): Promise<Array<UserProfile>>;
    placeOrder(input: OrderInput): Promise<OrderId>;
    postReview(input: ReviewInput): Promise<ReviewId>;
    saveCallerUserProfile(input: UserProfileInput): Promise<void>;
    searchFoodItems(filters: SearchFilters): Promise<Array<FoodItem>>;
    seedSampleData(): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    softDeleteUser(userId: UserId): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateFoodItem(foodItemId: FoodItemId, input: FoodItemInput): Promise<void>;
    updateOrderStatus(orderId: OrderId, newStatus: OrderStatus): Promise<void>;
    updateRestaurant(restaurantId: RestaurantId, input: RestaurantInput): Promise<void>;
}
import type { DietaryTag as _DietaryTag, ExternalBlob as _ExternalBlob, FoodItem as _FoodItem, FoodItemId as _FoodItemId, FoodItemInput as _FoodItemInput, OperatingHours as _OperatingHours, Order as _Order, OrderId as _OrderId, OrderInput as _OrderInput, OrderItem as _OrderItem, OrderItemInput as _OrderItemInput, OrderStatus as _OrderStatus, PaymentStatus as _PaymentStatus, Restaurant as _Restaurant, RestaurantId as _RestaurantId, RestaurantInput as _RestaurantInput, RestaurantRatingStats as _RestaurantRatingStats, RestaurantSummary as _RestaurantSummary, SearchFilters as _SearchFilters, SortOption as _SortOption, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: UserId, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmOrderPayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmOrderPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmOrderPayment(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createFoodItem(arg0: FoodItemInput): Promise<FoodItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFoodItem(await to_candid_FoodItemInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFoodItem(await to_candid_FoodItemInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRestaurant(arg0: RestaurantInput): Promise<RestaurantId> {
        if (this.processError) {
            try {
                const result = await this.actor.createRestaurant(await to_candid_RestaurantInput_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRestaurant(await to_candid_RestaurantInput_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteFoodItem(arg0: FoodItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodItem(arg0);
            return result;
        }
    }
    async deleteRestaurant(arg0: RestaurantId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRestaurant(arg0);
            return result;
        }
    }
    async deleteReview(arg0: ReviewId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodItem(arg0: FoodItemId): Promise<FoodItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodItem(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodItem(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: RestaurantId): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantRatingStats(arg0: RestaurantId): Promise<RestaurantRatingStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantRatingStats(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantRatingStats(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllOrders(arg0: RestaurantId | null, arg1: OrderStatus | null): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllReviews();
            return result;
        }
    }
    async listFoodItems(arg0: RestaurantId): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFoodItems(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFoodItems(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyOrders(arg0: OrderStatus | null): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRestaurantReviews(arg0: RestaurantId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRestaurantReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRestaurantReviews(arg0);
            return result;
        }
    }
    async listRestaurants(arg0: SearchFilters | null): Promise<Array<RestaurantSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRestaurants(to_candid_opt_n55(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRestaurants(to_candid_opt_n55(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(arg0: UserRole | null): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers(to_candid_opt_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers(to_candid_opt_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: OrderInput): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_OrderInput_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_OrderInput_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async postReview(arg0: ReviewInput): Promise<ReviewId> {
        if (this.processError) {
            try {
                const result = await this.actor.postReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postReview(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchFoodItems(arg0: SearchFilters): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoodItems(to_candid_SearchFilters_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoodItems(to_candid_SearchFilters_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async softDeleteUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.softDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.softDeleteUser(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateFoodItem(arg0: FoodItemId, arg1: FoodItemInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFoodItem(arg0, await to_candid_FoodItemInput_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFoodItem(arg0, await to_candid_FoodItemInput_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRestaurant(arg0: RestaurantId, arg1: RestaurantInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurant(arg0, await to_candid_RestaurantInput_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurant(arg0, await to_candid_RestaurantInput_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DietaryTag_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietaryTag): DietaryTag {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FoodItem_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodItem): Promise<FoodItem> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_RestaurantSummary_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantSummary): Promise<RestaurantSummary> {
    return await from_candid_record_n62(_uploadFile, _downloadFile, value);
}
async function from_candid_Restaurant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Promise<Restaurant> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodItem]): Promise<FoodItem | null> {
    return value.length === 0 ? null : await from_candid_FoodItem_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Promise<Restaurant | null> {
    return value.length === 0 ? null : await from_candid_Restaurant_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantRatingStats]): RestaurantRatingStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    isDeleted: boolean;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    phone: string;
    defaultAddress: string;
}): {
    id: UserId;
    isDeleted: boolean;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    phone: string;
    defaultAddress: string;
} {
    return {
        id: value.id,
        isDeleted: value.isDeleted,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n23(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        defaultAddress: value.defaultAddress
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FoodItemId;
    name: string;
    createdAt: _Timestamp;
    isAvailable: boolean;
    description: string;
    restaurantId: _RestaurantId;
    updatedAt: _Timestamp;
    dietaryTags: Array<_DietaryTag>;
    category: string;
    image: _ExternalBlob;
    price: bigint;
}): Promise<{
    id: FoodItemId;
    name: string;
    createdAt: Timestamp;
    isAvailable: boolean;
    description: string;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    dietaryTags: Array<DietaryTag>;
    category: string;
    image: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        isAvailable: value.isAvailable,
        description: value.description,
        restaurantId: value.restaurantId,
        updatedAt: value.updatedAt,
        dietaryTags: from_candid_vec_n30(_uploadFile, _downloadFile, value.dietaryTags),
        category: value.category,
        image: await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    taxes: bigint;
    deliveryAddress: string;
    total: bigint;
    paymentStatus: _PaymentStatus;
    deliveryFee: bigint;
    createdAt: _Timestamp;
    restaurantId: _RestaurantId;
    updatedAt: _Timestamp;
    specialInstructions: string;
    restaurantName: string;
    customerId: _UserId;
    phone: string;
    items: Array<_OrderItem>;
    stripeSessionId: [] | [string];
    subtotal: bigint;
}): {
    id: OrderId;
    status: OrderStatus;
    taxes: bigint;
    deliveryAddress: string;
    total: bigint;
    paymentStatus: PaymentStatus;
    deliveryFee: bigint;
    createdAt: Timestamp;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    specialInstructions: string;
    restaurantName: string;
    customerId: UserId;
    phone: string;
    items: Array<OrderItem>;
    stripeSessionId?: string;
    subtotal: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n37(_uploadFile, _downloadFile, value.status),
        taxes: value.taxes,
        deliveryAddress: value.deliveryAddress,
        total: value.total,
        paymentStatus: from_candid_PaymentStatus_n39(_uploadFile, _downloadFile, value.paymentStatus),
        deliveryFee: value.deliveryFee,
        createdAt: value.createdAt,
        restaurantId: value.restaurantId,
        updatedAt: value.updatedAt,
        specialInstructions: value.specialInstructions,
        restaurantName: value.restaurantName,
        customerId: value.customerId,
        phone: value.phone,
        items: value.items,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.stripeSessionId)),
        subtotal: value.subtotal
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RestaurantId;
    deliveryFee: bigint;
    ownerId: _UserId;
    name: string;
    createdAt: _Timestamp;
    cuisineType: string;
    description: string;
    isActive: boolean;
    deliveryTimeMinutes: bigint;
    updatedAt: _Timestamp;
    address: string;
    minimumOrder: bigint;
    image: _ExternalBlob;
    phone: string;
    operatingHours: _OperatingHours;
}): Promise<{
    id: RestaurantId;
    deliveryFee: bigint;
    ownerId: UserId;
    name: string;
    createdAt: Timestamp;
    cuisineType: string;
    description: string;
    isActive: boolean;
    deliveryTimeMinutes: bigint;
    updatedAt: Timestamp;
    address: string;
    minimumOrder: bigint;
    image: ExternalBlob;
    phone: string;
    operatingHours: OperatingHours;
}> {
    return {
        id: value.id,
        deliveryFee: value.deliveryFee,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        cuisineType: value.cuisineType,
        description: value.description,
        isActive: value.isActive,
        deliveryTimeMinutes: value.deliveryTimeMinutes,
        updatedAt: value.updatedAt,
        address: value.address,
        minimumOrder: value.minimumOrder,
        image: await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value.image),
        phone: value.phone,
        operatingHours: value.operatingHours
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RestaurantId;
    deliveryFee: bigint;
    name: string;
    cuisineType: string;
    isActive: boolean;
    deliveryTimeMinutes: bigint;
    averageRating: number;
    minimumOrder: bigint;
    image: _ExternalBlob;
    reviewCount: bigint;
}): Promise<{
    id: RestaurantId;
    deliveryFee: bigint;
    name: string;
    cuisineType: string;
    isActive: boolean;
    deliveryTimeMinutes: bigint;
    averageRating: number;
    minimumOrder: bigint;
    image: ExternalBlob;
    reviewCount: bigint;
}> {
    return {
        id: value.id,
        deliveryFee: value.deliveryFee,
        name: value.name,
        cuisineType: value.cuisineType,
        isActive: value.isActive,
        deliveryTimeMinutes: value.deliveryTimeMinutes,
        averageRating: value.averageRating,
        minimumOrder: value.minimumOrder,
        image: await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value.image),
        reviewCount: value.reviewCount
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    restaurant_owner: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "customer" in value ? UserRole.customer : "restaurant_owner" in value ? UserRole.restaurant_owner : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veg: null;
} | {
    halal: null;
} | {
    vegan: null;
} | {
    dairy_free: null;
} | {
    spicy: null;
} | {
    gluten_free: null;
}): DietaryTag {
    return "veg" in value ? DietaryTag.veg : "halal" in value ? DietaryTag.halal : "vegan" in value ? DietaryTag.vegan : "dairy_free" in value ? DietaryTag.dairy_free : "spicy" in value ? DietaryTag.spicy : "gluten_free" in value ? DietaryTag.gluten_free : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    out_for_delivery: null;
} | {
    delivered: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "out_for_delivery" in value ? OrderStatus.out_for_delivery : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietaryTag>): Array<DietaryTag> {
    return value.map((x)=>from_candid_DietaryTag_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodItem>): Promise<Array<FoodItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FoodItem_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantSummary>): Promise<Array<RestaurantSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_RestaurantSummary_n61(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n21(_uploadFile, _downloadFile, x));
}
function to_candid_DietaryTag_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): _DietaryTag {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FoodItemInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodItemInput): Promise<_FoodItemInput> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_OrderInput_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
async function to_candid_RestaurantInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantInput): Promise<_RestaurantInput> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_SearchFilters_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilters): _SearchFilters {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_SortOption_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption): _SortOption {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantId | null): [] | [_RestaurantId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus | null): [] | [_OrderStatus] {
    return value === null ? candid_none() : candid_some(to_candid_OrderStatus_n51(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilters | null): [] | [_SearchFilters] {
    return value === null ? candid_none() : candid_some(to_candid_SearchFilters_n56(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole | null): [] | [_UserRole] {
    return value === null ? candid_none() : candid_some(to_candid_UserRole_n10(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    restaurantId: RestaurantId;
    dietaryTags: Array<DietaryTag>;
    category: string;
    image: ExternalBlob;
    price: bigint;
}): Promise<{
    name: string;
    description: string;
    restaurantId: _RestaurantId;
    dietaryTags: Array<_DietaryTag>;
    category: string;
    image: _ExternalBlob;
    price: bigint;
}> {
    return {
        name: value.name,
        description: value.description,
        restaurantId: value.restaurantId,
        dietaryTags: to_candid_vec_n14(_uploadFile, _downloadFile, value.dietaryTags),
        category: value.category,
        image: await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveryFee: bigint;
    ownerId: UserId;
    name: string;
    cuisineType: string;
    description: string;
    deliveryTimeMinutes: bigint;
    address: string;
    minimumOrder: bigint;
    image: ExternalBlob;
    phone: string;
    operatingHours: OperatingHours;
}): Promise<{
    deliveryFee: bigint;
    ownerId: _UserId;
    name: string;
    cuisineType: string;
    description: string;
    deliveryTimeMinutes: bigint;
    address: string;
    minimumOrder: bigint;
    image: _ExternalBlob;
    phone: string;
    operatingHours: _OperatingHours;
}> {
    return {
        deliveryFee: value.deliveryFee,
        ownerId: value.ownerId,
        name: value.name,
        cuisineType: value.cuisineType,
        description: value.description,
        deliveryTimeMinutes: value.deliveryTimeMinutes,
        address: value.address,
        minimumOrder: value.minimumOrder,
        image: await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.image),
        phone: value.phone,
        operatingHours: value.operatingHours
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minRating?: number;
    sortBy?: SortOption;
    cuisineType?: string;
    maxPrice?: bigint;
    dietaryTags: Array<DietaryTag>;
    category?: string;
    minPrice?: bigint;
    searchQuery?: string;
}): {
    minRating: [] | [number];
    sortBy: [] | [_SortOption];
    cuisineType: [] | [string];
    maxPrice: [] | [bigint];
    dietaryTags: Array<_DietaryTag>;
    category: [] | [string];
    minPrice: [] | [bigint];
    searchQuery: [] | [string];
} {
    return {
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        sortBy: value.sortBy ? candid_some(to_candid_SortOption_n58(_uploadFile, _downloadFile, value.sortBy)) : candid_none(),
        cuisineType: value.cuisineType ? candid_some(value.cuisineType) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        dietaryTags: to_candid_vec_n14(_uploadFile, _downloadFile, value.dietaryTags),
        category: value.category ? candid_some(value.category) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveryAddress: string;
    restaurantId: RestaurantId;
    specialInstructions: string;
    phone: string;
    items: Array<OrderItemInput>;
    stripeSessionId?: string;
}): {
    deliveryAddress: string;
    restaurantId: _RestaurantId;
    specialInstructions: string;
    phone: string;
    items: Array<_OrderItemInput>;
    stripeSessionId: [] | [string];
} {
    return {
        deliveryAddress: value.deliveryAddress,
        restaurantId: value.restaurantId,
        specialInstructions: value.specialInstructions,
        phone: value.phone,
        items: value.items,
        stripeSessionId: value.stripeSessionId ? candid_some(value.stripeSessionId) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    customer: null;
} | {
    restaurant_owner: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.customer ? {
        customer: null
    } : value == UserRole.restaurant_owner ? {
        restaurant_owner: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): {
    veg: null;
} | {
    halal: null;
} | {
    vegan: null;
} | {
    dairy_free: null;
} | {
    spicy: null;
} | {
    gluten_free: null;
} {
    return value == DietaryTag.veg ? {
        veg: null
    } : value == DietaryTag.halal ? {
        halal: null
    } : value == DietaryTag.vegan ? {
        vegan: null
    } : value == DietaryTag.dairy_free ? {
        dairy_free: null
    } : value == DietaryTag.spicy ? {
        spicy: null
    } : value == DietaryTag.gluten_free ? {
        gluten_free: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    out_for_delivery: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.out_for_delivery ? {
        out_for_delivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption): {
    deliveryTime: null;
} | {
    priceDesc: null;
} | {
    rating: null;
} | {
    priceAsc: null;
} {
    return value == SortOption.deliveryTime ? {
        deliveryTime: null
    } : value == SortOption.priceDesc ? {
        priceDesc: null
    } : value == SortOption.rating ? {
        rating: null
    } : value == SortOption.priceAsc ? {
        priceAsc: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DietaryTag>): Array<_DietaryTag> {
    return value.map((x)=>to_candid_DietaryTag_n15(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
